#!/usr/bin/env python3
# Copyright 2026 Antoni Martorell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Checks the output of replaying the data generated by scripts/make_test_ubx.py."""

import math
import threading
import time
import unittest

import rospy
import rostest
from sensor_msgs.msg import Imu, NavSatFix
from ublox_x20d_msgs.msg import NavDAHeading

# Epochs 0-9 of the sample; see scripts/make_test_ubx.py.
EXPECTED_DAHEADING = 9   # epoch 7 (payload version 0x01) is dropped by the driver
EXPECTED_FIX = 10
EXPECTED_IMU = 7         # epochs 5 (float) and 6 (heading not valid) are also dropped
TOL = 1e-6


def yaw_pitch(q):
    yaw = math.atan2(2.0 * (q.w * q.z + q.x * q.y), 1.0 - 2.0 * (q.y * q.y + q.z * q.z))
    pitch = math.asin(max(-1.0, min(1.0, 2.0 * (q.w * q.y - q.z * q.x))))
    return yaw, pitch


class ReplayTest(unittest.TestCase):
    def setUp(self):
        self.lock = threading.Lock()
        self.daheading = []
        self.fix = []
        self.imu = []
        rospy.Subscriber('/ublox_x20d/nav_daheading', NavDAHeading, self.store(self.daheading))
        rospy.Subscriber('/ublox_x20d/fix', NavSatFix, self.store(self.fix))
        rospy.Subscriber('/heading_imu/imu', Imu, self.store(self.imu))
        self.check_driver = rospy.get_param('~check_driver_topics', True)

    def store(self, target):
        def callback(msg):
            with self.lock:
                target.append(msg)
        return callback

    def wait_for_counts(self, timeout):
        deadline = time.time() + timeout
        while time.time() < deadline and not rospy.is_shutdown():
            with self.lock:
                done = len(self.imu) >= EXPECTED_IMU and len(self.daheading) >= EXPECTED_DAHEADING
                if self.check_driver:
                    done = done and len(self.fix) >= EXPECTED_FIX
            if done:
                break
            time.sleep(0.1)
        time.sleep(1.0)  # anything extra would arrive now

    def test_replay(self):
        self.wait_for_counts(40.0)
        with self.lock:
            self.assertEqual(len(self.daheading), EXPECTED_DAHEADING)
            self.assertEqual(len(self.imu), EXPECTED_IMU)
            if self.check_driver:
                self.assertEqual(len(self.fix), EXPECTED_FIX)
                self.assertTrue(all(f.status.status == 2 for f in self.fix))
                self.assertAlmostEqual(self.fix[0].latitude, 39.5712345 + 67e-9, places=9)
                self.assertAlmostEqual(self.fix[0].longitude, 2.6461234 - 45e-9, places=9)

            self.assertTrue(all(m.version == 2 for m in self.daheading))

            # epochs 0-4: 90 deg (east) level -> yaw 0, pitch 0
            for imu in self.imu[:5]:
                yaw, pitch = yaw_pitch(imu.orientation)
                self.assertAlmostEqual(yaw, 0.0, delta=TOL)
                self.assertAlmostEqual(pitch, 0.0, delta=TOL)
                self.assertEqual(imu.orientation_covariance[0], 1e6)
                self.assertAlmostEqual(imu.orientation_covariance[8], math.radians(0.61) ** 2, delta=1e-12)
                self.assertEqual(imu.angular_velocity_covariance[0], -1.0)

            # epoch 8: 45 deg, forward antenna 100 mm lower -> yaw 45 deg, positive pitch
            yaw, pitch = yaw_pitch(self.imu[5].orientation)
            self.assertAlmostEqual(yaw, math.radians(45.0), delta=TOL)
            self.assertAlmostEqual(pitch, math.asin(100.0 / 995.0), delta=TOL)

            # epoch 9: 270 deg (west) -> yaw +/-pi
            yaw, pitch = yaw_pitch(self.imu[6].orientation)
            self.assertAlmostEqual(abs(yaw), math.pi, delta=TOL)


if __name__ == '__main__':
    rospy.init_node('replay_checker')
    rostest.rosrun('ublox_x20d_driver', 'replay_checker', ReplayTest)
